function  GUI = UnifiedField_GUI_Initialization(first_initialization)
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% UnifiedField_GUI_Initialization()
%
% Initialize the GUI (Graphical User Interface) related parameters and
% save a copy to the corresponding EVENT structure. The EVENT structure
% will be updated during event interrupt call-backs. At the start of the
% screen draw the EVENT structure is the copied back to the GUI structure
% so that GUI parameters are consistent during screen-draw.
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


global EVENT       %   Version of GUI with real time updated values


% ==================================================================================================
%%                 RESERVE STRUCTURES FOR GUI HANDLES
% ==================================================================================================

if first_initialization
GUI.handles                                = [];
GUI.figure_Main                            = [];
GUI.Timeline_Cursor_Position               = [0,0,0,0];
else
GUI.handles                                = EVENT.handles;
GUI.figure_Main                            = EVENT.figure_Main;
GUI.Timeline_Cursor_Position               = EVENT.Timeline_Cursor_Position;
end

% ==================================================================================================
%%                 DEFINE SIGNALS (FLAGS WHICH ARE ONY A SINGLE CYCLE ACTIVE)
% ==================================================================================================

GUI.signal_GUI_start                       = true;                   %Active during first cycle
GUI.signal_GUI_end                         = false;                  %Active during last cycle
GUI.signal_GUI_data_input_event            = true;                   %GUI data input event has occured or 1st cycle
GUI.signal_GUI_visualization_event         = false;                  %GUI visualization event has occured
GUI.signal_GUI_command_event               = false;                  %GUI command event has occured
GUI.signal_GUI_bilinear_gamma_event        = true;                   %Gamma usage changed, modify GUI layout


% ==================================================================================================
%%                 INITIALIZE GUI ELEMENTS
% ==================================================================================================

GUI.color(1,1:3)                           =  [255 255 255]/255;  % white
GUI.color(2,1:3)                           =  [245 245 245]/255;  % light gray
GUI.color(3,1:3)                           =  [245 235 235]/255;  % light red
GUI.color(4,1:3)                           =  [228 240 230]/255;  % light green
GUI.color(5,1:3)                           =  [222 235 250]/255;  % light blue
GUI.color(6,1:3)                           =  [255 247 235]/255;  % light yellow
GUI.color(7,1:3)                           =  [255 242 222]/255;  % light yellow 2

% ==================================================================================================
%%                 INITIALIZE GUI PARAMETERS
% ==================================================================================================

GUI.running                                = true;
GUI.slider_Time_value                      = 1;
GUI.Play_Timeline                          = false;
GUI.Play_Timeline_Speed                    = 1;
GUI.MovieRecordingRequested                = false;
GUI.VideoFileName                          = 'MyVideoFileName';
GUI.Sequence_choice                        = 1;
GUI.Visualization_choice                   = 2;  
GUI.Show_Spinor_choice                     = 2;       % 1 = X Y Z, 2 = Sx Sy Sz
GUI.Generator_Potential_or_Force           = [1,1,1];
GUI.Generator_Select                       = [2,2,2];
GUI.Generator_Shown                        = [-1,-1,-1];
GUI.Generator_FieldNr                      = [1,2,3];
GUI.Generator_Generation                   = [1,1,1];
GUI.Generator_ChargeSign                   = [-1,-1,-1];
GUI.Generator_ChargeValue                  = [3,3,3];
GUI.Generator_LorR                         = [1,1,1];
GUI.EW_Boson_Generator_choice              = [1,1,1];
GUI.Poincare_Generator_choice              = [1,1,1];
GUI.Internal_Generator_choice              = [1,1,1];
GUI.Sum_Generators                         = [true, false,false;false,true, false;false,false,true];
GUI.Lepton_Mass                            = [0.5,0.75,1.0];
GUI.Fermion_Type_choice                    = [1,2,3];
GUI.Fermion_Ninv_choice                    = [1,1,1]; % +1 normal ,    -1 is neutrino charge inverted
GUI.Fermion_Anti_choice                    = [1,1,1]; % particle,      -1 is antiparticle
GUI.Fermion_Pinv_choice                    = [1,1,1]; % +1 normal ,    -1 is parity inverted
GUI.Fermion_Tinv_choice                    = [1,1,1]; % +1 normal ,    -1 is time inverted
GUI.Fermion_Mass_choice                    = [1,1,1]; % positive mass, -1 is negative mass
GUI.Fermion_Pseu_choice                    = [1,1,1]; % +1 normal,     -1 is pseudo particle
GUI.Spin_Direction_choice                  = [2,2,2];
GUI.Boost_Direction_choice                 = [1,1,1];
GUI.Boost_Amount_choice                    = [1,1,1];
GUI.Boost_Amount_step                      = [1,1,1];
GUI.Phase_or_Color_choice                  = [1,1,1];
GUI.Lagrangian_Coupling_Method             =  1;
GUI.Lagrangian_Coupling_Overrule           = [false,false,false];
GUI.Lagrangian_Coupling_Scale              = [1,1,1];
GUI.Generator_minus                        = [false,false,false];
GUI.Use_generators_for_all_particles       =  false;
GUI.Show_Operator_Field_choice             = 1;  % n = Operator 1,2 or 3,
GUI.Decompose_Generator                    = false;
GUI.Show_Bilinear_Field_choice             = 1;  % n = Bilinear 1,2 or 3,
GUI.Enable_Bilinear_Field_choice           = false;
GUI.Bilinear_Input_Fields_choice           = [ 1 1 ; 2 2 ; 3 3 ];
GUI.Bilinear_Field_Matrix_gamma            = true;
GUI.Bilinear_Construction_Choice           = [ 1 1 1 ];
GUI.Table_Data_TableNr                     = 0;
GUI.Table_Data_Indices                     = [ 1 1 ];
GUI.Show_Vector_Trajectories               = false;
GUI.Show_No_Spinors                        = [false,false,false];
GUI.Show_Spinor_Current                    = [true, true, true ];
GUI.Show_Spinor_Meshes                     = [true, true, true ];
GUI.Boson_Vector_Select                    = [true, false,false,false ; ...
                                              false,true, true, true  ; ...
                                              false,false,false,false ; ...
                                              false,false,false,false];                                              
GUI.Vector_Colors                          = [ 1.0  1.0  0.6 ; 1.0  0.8  0.4 ; 1.0  0.6  0.2 ; 1.0  0.4  0.0 ; ...
                                               0.6  1.0  0.8 ; 0.2  1.0  0.6 ; 0.0  1.0  0.0 ; 0.0  0.8  0.2 ; ...
                                               0.8  1.0  1.0 ; 0.6  0.8  1.0 ; 0.4  0.6  1.0 ; 0.4  0.4  1.0 ; ...
                                               1.0  0.8  1.0 ; 1.0  0.6  0.6 ; 1.0  0.4  0.4 ; 1.0  0.2  0.0 ]; 
GUI.W_Boson_Type_12_not_pm                 = +1;                          
GUI.Fermion_Gen_Select                     = [false, true, false, false ];
GUI.Enable_Accumulation                    =  false;
GUI.Boson_Potential_popup_list             = {};
GUI.Boson_Force_popup_list                 = {};


% ==================================================================================================
%%  Copy all GUI parameters to the EVENT parameters
% ==================================================================================================

EVENT = GUI;  % The EVENT parameters are updated by interrupt driven call-backs





% ==================================================================================================
%%                 START THE GRAPHICAL USER INTERFACE
% ==================================================================================================

if first_initialization

UnifiedField_GUI();

movegui('northwest');

GUI.handles                    =      EVENT.handles;
GUI.figure_Main                =      EVENT.figure_Main;
GUI.Timeline_Cursor_Position   =      get(GUI.handles.uipanel_Cursor_Line,'Position');

end


% ==================================================================================================
%%  The GUI Handles are now defined
% ==================================================================================================

                                 


GUI.handles_Spinor_Axes        =    [ GUI.handles.axes_Left_Spinor_1_1,      ...
                                      GUI.handles.axes_Left_Spinor_2_1,      ...
                                      GUI.handles.axes_Right_Spinor_1_1,     ...
                                      GUI.handles.axes_Right_Spinor_2_1,     ...
                                      GUI.handles.axes_Left_Spinor_1_2,      ...
                                      GUI.handles.axes_Left_Spinor_2_2,      ...
                                      GUI.handles.axes_Right_Spinor_1_2,     ...
                                      GUI.handles.axes_Right_Spinor_2_2,     ...
                                      GUI.handles.axes_Left_Spinor_1_3,      ...
                                      GUI.handles.axes_Left_Spinor_2_3,      ...
                                      GUI.handles.axes_Right_Spinor_1_3,     ...
                                      GUI.handles.axes_Right_Spinor_2_3  ];
    
GUI.handles_Timeline_Axes      =    [ GUI.handles.axes_timeline_1,  ...
                                      GUI.handles.axes_timeline_2,  ...
                                      GUI.handles.axes_timeline_3,  ...
                                      GUI.handles.axes_timeline_4,  ...
                                      GUI.handles.axes_timeline_5  ];  
                             
GUI.handles_Timeline_Values      =  [ GUI.handles.text_Timeline_Values11, ...
                                      GUI.handles.text_Timeline_Values12, ...
                                      GUI.handles.text_Timeline_Values13, ...
                                      GUI.handles.text_Timeline_Values14, ...
                                      GUI.handles.text_Timeline_Values21, ...
                                      GUI.handles.text_Timeline_Values22, ...
                                      GUI.handles.text_Timeline_Values23, ...
                                      GUI.handles.text_Timeline_Values24, ...
                                      GUI.handles.text_Timeline_Values31, ...
                                      GUI.handles.text_Timeline_Values32, ...
                                      GUI.handles.text_Timeline_Values33, ...
                                      GUI.handles.text_Timeline_Values34, ...
                                      GUI.handles.text_Timeline_Values41, ...
                                      GUI.handles.text_Timeline_Values42, ...
                                      GUI.handles.text_Timeline_Values43, ...
                                      GUI.handles.text_Timeline_Values44, ...
                                      GUI.handles.text_Timeline_Values51, ...
                                      GUI.handles.text_Timeline_Values52, ...
                                      GUI.handles.text_Timeline_Values53, ...
                                      GUI.handles.text_Timeline_Values54  ];
                                 
                                                                           
GUI.handles_Boson_Vectors        =  [ GUI.handles.checkbox_Axial_current1,  ...
                                      GUI.handles.checkbox_Vector_current1, ...
                                      GUI.handles.checkbox_Polarization1,   ...                                 
                                      GUI.handles.checkbox_Magnetization1,  ...
                                      GUI.handles.checkbox_Axial_current2,  ...
                                      GUI.handles.checkbox_Vector_current2, ...
                                      GUI.handles.checkbox_Polarization2,   ...                                 
                                      GUI.handles.checkbox_Magnetization2,  ...
                                      GUI.handles.checkbox_Axial_current3,  ...
                                      GUI.handles.checkbox_Vector_current3, ...
                                      GUI.handles.checkbox_Polarization3,   ...                                 
                                      GUI.handles.checkbox_Magnetization3,  ...
                                      GUI.handles.checkbox_Axial_current4,  ...
                                      GUI.handles.checkbox_Vector_current4, ...
                                      GUI.handles.checkbox_Polarization4,   ...                                 
                                      GUI.handles.checkbox_Magnetization4 ];
                                  
GUI.handles_Fermion_Field_Type    = [ GUI.handles.popupmenu_Select_Fermion_Field_Type1, ...
                                      GUI.handles.popupmenu_Select_Fermion_Field_Type2, ...
                                      GUI.handles.popupmenu_Select_Fermion_Field_Type3 ];
                                  
GUI.handles_Fermion_Spin_Dir      = [ GUI.handles.popupmenu_Select_Fermion_Spin_Direction1, ...
                                      GUI.handles.popupmenu_Select_Fermion_Spin_Direction2, ...
                                      GUI.handles.popupmenu_Select_Fermion_Spin_Direction3 ];
                                  
GUI.handles_Fermion_Boost_Dir     = [ GUI.handles.popupmenu_Select_Fermion_Boost_Direction1, ...
                                      GUI.handles.popupmenu_Select_Fermion_Boost_Direction2, ...
                                      GUI.handles.popupmenu_Select_Fermion_Boost_Direction3 ];
                                  
GUI.handles_Fermion_Boost_Amount  = [ GUI.handles.pushbutton_Fermion_BoostAmount1, ...
                                      GUI.handles.pushbutton_Fermion_BoostAmount2, ...
                                      GUI.handles.pushbutton_Fermion_BoostAmount3 ];                                 

GUI.handles_Fermion_Phase_Color   = [ GUI.handles.popupmenu_Select_Fermion_Phase_or_Color1, ...
                                      GUI.handles.popupmenu_Select_Fermion_Phase_or_Color2, ...
                                      GUI.handles.popupmenu_Select_Fermion_Phase_or_Color3 ];

GUI.handles_Boson_Field_Gen       = [ GUI.handles.popupmenu_Select_Boson_Field_Generator1, ...
                                      GUI.handles.popupmenu_Select_Boson_Field_Generator2, ...
                                      GUI.handles.popupmenu_Select_Boson_Field_Generator3 ];

GUI.handles_Poincare_Generator    = [ GUI.handles.popupmenu_Select_Poincare_Field_Generator1, ...                                  
                                      GUI.handles.popupmenu_Select_Poincare_Field_Generator2, ...                                  
                                      GUI.handles.popupmenu_Select_Poincare_Field_Generator3 ];                           
                                  
GUI.handles_Internal_Generator    = [ GUI.handles.popupmenu_Select_Internal_Field_Generator1, ...                                  
                                      GUI.handles.popupmenu_Select_Internal_Field_Generator2, ...                                  
                                      GUI.handles.popupmenu_Select_Internal_Field_Generator3 ];                           
                                  
GUI.handles_Lagrangian_Coupling   = [ GUI.handles.text_Lagrangian_Coupling_value1, ...
                                      GUI.handles.text_Lagrangian_Coupling_value2, ...
                                      GUI.handles.text_Lagrangian_Coupling_value3 ];

GUI.handles_Lagrangian_Axes       = [ GUI.handles.axes_Lagrangian_Coupling1, ...
                                      GUI.handles.axes_Lagrangian_Coupling2, ...
                                      GUI.handles.axes_Lagrangian_Coupling3 ];

GUI.handles_Lagrangian_Overrule   = [ GUI.handles.checkbox_Lagrangian_Coupling_Overrule1, ...
                                      GUI.handles.checkbox_Lagrangian_Coupling_Overrule2, ...
                                      GUI.handles.checkbox_Lagrangian_Coupling_Overrule3 ];
                                  
GUI.handles_Generator_Minus       = [ GUI.handles.checkbox_Generator_minus1, ...
                                      GUI.handles.checkbox_Generator_minus2, ...
                                      GUI.handles.checkbox_Generator_minus3 ];
                                  
GUI.handles_Lagrangian_Slider     = [ GUI.handles.slider_Lagrangian_Coupling1, ...
                                      GUI.handles.slider_Lagrangian_Coupling2, ...
                                      GUI.handles.slider_Lagrangian_Coupling3 ];
                                  
GUI.handles_SumGenerators         = [ GUI.handles.checkbox_SumGenerators11, ...
                                      GUI.handles.checkbox_SumGenerators12, ...
                                      GUI.handles.checkbox_SumGenerators13, ...
                                      GUI.handles.checkbox_SumGenerators21, ...
                                      GUI.handles.checkbox_SumGenerators22, ...
                                      GUI.handles.checkbox_SumGenerators23, ...
                                      GUI.handles.checkbox_SumGenerators31, ...
                                      GUI.handles.checkbox_SumGenerators32, ...
                                      GUI.handles.checkbox_SumGenerators33 ];
                                  
GUI.handles_edit_Lepton_Mass      = [ GUI.handles.edit_Lepton_Mass11, ...
                                      GUI.handles.edit_Lepton_Mass12, ...
                                      GUI.handles.edit_Lepton_Mass13, ...
                                      GUI.handles.edit_Lepton_Mass21, ...
                                      GUI.handles.edit_Lepton_Mass22, ...
                                      GUI.handles.edit_Lepton_Mass23, ...
                                      GUI.handles.edit_Lepton_Mass31, ...
                                      GUI.handles.edit_Lepton_Mass32, ...
                                      GUI.handles.edit_Lepton_Mass33 ];
                                                                  
GUI.handles_panel_Field_Selects   = [ GUI.handles.uipanel_Field1_Selections, ...
                                      GUI.handles.uipanel_Field2_Selections, ...
                                      GUI.handles.uipanel_Field3_Selections ];

GUI.handles_Potential_or_Force    = [ GUI.handles.pushbutton_Gen_Potential_or_Force1, ... 
                                      GUI.handles.pushbutton_Gen_Potential_or_Force2, ... 
                                      GUI.handles.pushbutton_Gen_Potential_or_Force3 ];
                                  
GUI.handles_Text_Boson_Field_Gen  = [ GUI.handles.text_Select_Boson_Field_Generator1, ... 
                                      GUI.handles.text_Select_Boson_Field_Generator2, ... 
                                      GUI.handles.text_Select_Boson_Field_Generator3 ];
                               
GUI.handles_Fermion_Ninv          = [ GUI.handles.pushbutton_Fermion_Ninv1, ... 
                                      GUI.handles.pushbutton_Fermion_Ninv2, ... 
                                      GUI.handles.pushbutton_Fermion_Ninv3 ];
                                                         
GUI.handles_Fermion_Cinv          = [ GUI.handles.pushbutton_Fermion_Anti1, ... 
                                      GUI.handles.pushbutton_Fermion_Anti2, ... 
                                      GUI.handles.pushbutton_Fermion_Anti3 ];
                                                         
GUI.handles_Fermion_Pinv          = [ GUI.handles.pushbutton_Fermion_Pinv1, ... 
                                      GUI.handles.pushbutton_Fermion_Pinv2, ... 
                                      GUI.handles.pushbutton_Fermion_Pinv3 ];
                                                         
GUI.handles_Fermion_Tinv          = [ GUI.handles.pushbutton_Fermion_Tinv1, ... 
                                      GUI.handles.pushbutton_Fermion_Tinv2, ... 
                                      GUI.handles.pushbutton_Fermion_Tinv3 ];
                                                         
GUI.handles_Fermion_Pseu          = [ GUI.handles.pushbutton_Fermion_Pseu1, ... 
                                      GUI.handles.pushbutton_Fermion_Pseu2, ... 
                                      GUI.handles.pushbutton_Fermion_Pseu3 ];
                                                         
GUI.handles_Fermion_Mass          = [ GUI.handles.pushbutton_Fermion_Mass1, ... 
                                      GUI.handles.pushbutton_Fermion_Mass2, ... 
                                      GUI.handles.pushbutton_Fermion_Mass3 ];
                                                         
GUI.handles_Generator_FieldNr     = [ GUI.handles.pushbutton_Generator_FieldNr1, ... 
                                      GUI.handles.pushbutton_Generator_FieldNr2, ... 
                                      GUI.handles.pushbutton_Generator_FieldNr3 ];
                                                         
GUI.handles_Generator_ChargeSign  = [ GUI.handles.pushbutton_Generator_ChargeSign1, ... 
                                      GUI.handles.pushbutton_Generator_ChargeSign2, ... 
                                      GUI.handles.pushbutton_Generator_ChargeSign3 ];
                             
GUI.handles_Generator_ChargeValue = [ GUI.handles.pushbutton_Generator_ChargeValue1, ... 
                                      GUI.handles.pushbutton_Generator_ChargeValue2, ... 
                                      GUI.handles.pushbutton_Generator_ChargeValue3 ];
                             
GUI.handles_Generator_Generation  = [ GUI.handles.pushbutton_Generator_Generation1, ... 
                                      GUI.handles.pushbutton_Generator_Generation2, ... 
                                      GUI.handles.pushbutton_Generator_Generation3 ];

GUI.handles_Generator_LorR        = [ GUI.handles.pushbutton_Generator_LorR1, ... 
                                      GUI.handles.pushbutton_Generator_LorR2, ... 
                                      GUI.handles.pushbutton_Generator_LorR3 ];

GUI.handles_GenSymbol_Image       = [ GUI.handles.axes_GenSymbol_Image1, ...
                                      GUI.handles.axes_GenSymbol_Image2, ...
                                      GUI.handles.axes_GenSymbol_Image3 ];
    
GUI.handles_GenSymbol_Hi_Indices  = [ GUI.handles.text_GenSymbol_Hi_Indices1, ...
                                      GUI.handles.text_GenSymbol_Hi_Indices2, ...
                                      GUI.handles.text_GenSymbol_Hi_Indices3 ];

GUI.handles_GenSymbol_Lo_Indices  = [ GUI.handles.text_GenSymbol_Lo_Indices1, ...
                                      GUI.handles.text_GenSymbol_Lo_Indices2, ...
                                      GUI.handles.text_GenSymbol_Lo_Indices3 ];
                                  
GUI.handles_Generator_Scale       = [ GUI.handles.text_Generator_Scale_factor1, ...
                                      GUI.handles.text_Generator_Scale_factor2, ...
                                      GUI.handles.text_Generator_Scale_factor3 ];
                                  
GUI.handles_Show_No_Spinors       = [ GUI.handles.checkbox_Show_No_Spinors1, ...
                                      GUI.handles.checkbox_Show_No_Spinors2, ...
                                      GUI.handles.checkbox_Show_No_Spinors3 ];
                                  
GUI.handles_Z_charge_Values       = [ GUI.handles.text_Z_charge_Value1, ...
                                      GUI.handles.text_Z_charge_Value2, ...
                                      GUI.handles.text_Z_charge_Value3 ];

GUI.handles_A_charge_Values       = [ GUI.handles.text_A_charge_Value1, ...
                                      GUI.handles.text_A_charge_Value2, ...
                                      GUI.handles.text_A_charge_Value3 ];
                                  
GUI.handles_W1charge_Values       = [ GUI.handles.text_W1charge_Value1, ...
                                      GUI.handles.text_W1charge_Value2, ...
                                      GUI.handles.text_W1charge_Value3 ];
                                                                  
GUI.handles_W2charge_Values       = [ GUI.handles.text_W2charge_Value1, ...
                                      GUI.handles.text_W2charge_Value2, ...
                                      GUI.handles.text_W2charge_Value3 ];
                                  
GUI.handles_Z_charge_VectorValues = [ GUI.handles.text_Z_charge_VectorValue1, ...
                                      GUI.handles.text_Z_charge_VectorValue2, ...
                                      GUI.handles.text_Z_charge_VectorValue3 ];

GUI.handles_A_charge_VectorValues = [ GUI.handles.text_A_charge_VectorValue1, ...
                                      GUI.handles.text_A_charge_VectorValue2, ...
                                      GUI.handles.text_A_charge_VectorValue3 ];
                                  
GUI.handles_W1charge_VectorValues = [ GUI.handles.text_W1charge_VectorValue1, ...
                                      GUI.handles.text_W1charge_VectorValue2, ...
                                      GUI.handles.text_W1charge_VectorValue3 ];
                                                                  
GUI.handles_W2charge_VectorValues = [ GUI.handles.text_W2charge_VectorValue1, ...
                                      GUI.handles.text_W2charge_VectorValue2, ...
                                      GUI.handles.text_W2charge_VectorValue3 ];
                                    
GUI.handles_Z_charge_AxialValues  = [ GUI.handles.text_Z_charge_AxialValue1, ...
                                      GUI.handles.text_Z_charge_AxialValue2, ...
                                      GUI.handles.text_Z_charge_AxialValue3 ];

GUI.handles_A_charge_AxialValues  = [ GUI.handles.text_A_charge_AxialValue1, ...
                                      GUI.handles.text_A_charge_AxialValue2, ...
                                      GUI.handles.text_A_charge_AxialValue3 ];
                                  
GUI.handles_W1charge_AxialValues  = [ GUI.handles.text_W1charge_AxialValue1, ...
                                      GUI.handles.text_W1charge_AxialValue2, ...
                                      GUI.handles.text_W1charge_AxialValue3 ];
                                                                  
GUI.handles_W2charge_AxialValues  = [ GUI.handles.text_W2charge_AxialValue1, ...
                                      GUI.handles.text_W2charge_AxialValue2, ...
                                      GUI.handles.text_W2charge_AxialValue3 ];
                                    
boson_popup_list =  get(GUI.handles.popupmenu_Select_Boson_Field_Generator0,'String');

GUI.Boson_Potential_popup_list    =   boson_popup_list( 1:17);
GUI.Boson_Force_popup_list        =   boson_popup_list(18:42);

set(GUI.handles_Boson_Field_Gen(1),'String',GUI.Boson_Potential_popup_list);
set(GUI.handles_Boson_Field_Gen(2),'String',GUI.Boson_Potential_popup_list);
set(GUI.handles_Boson_Field_Gen(3),'String',GUI.Boson_Potential_popup_list);
 


% ==================================================================================================
%%  Copy all GUI parameters to the EVENT parameters
% ==================================================================================================

EVENT = GUI;  % The EVENT parameters are updated by interrupt driven call-backs

% ==================================================================================================
%%  
% ==================================================================================================

if ~first_initialization
    
    for particle_nr =1:3

       set(GUI.handles_Potential_or_Force(particle_nr),         'String','POTENTIAL GENERATOR PROPORTIES'); 
       set(GUI.handles_Text_Boson_Field_Gen(particle_nr),       'String','Boson Potential Field Generator');
       set(GUI.handles_Fermion_Boost_Amount(particle_nr),       'String','+'); 
       set(GUI.handles_Fermion_Field_Type(particle_nr),         'Value',  GUI.Fermion_Type_choice(particle_nr));                                
       set(GUI.handles_Fermion_Spin_Dir(particle_nr),           'Value',  GUI.Spin_Direction_choice(particle_nr));                            
       set(GUI.handles_Fermion_Boost_Dir(particle_nr),          'Value',  GUI.Boost_Direction_choice(particle_nr)); 
       set(GUI.handles_Fermion_Phase_Color(particle_nr),        'Value',  GUI.Phase_or_Color_choice(particle_nr)); 
       set(GUI.handles_Boson_Field_Gen(particle_nr),            'String', GUI.Boson_Potential_popup_list);
       set(GUI.handles_Boson_Field_Gen(particle_nr),            'Value',  GUI.EW_Boson_Generator_choice(particle_nr)); 
       set(GUI.handles_Poincare_Generator(particle_nr),         'Value',  GUI.Poincare_Generator_choice(particle_nr));                                  
       set(GUI.handles_Internal_Generator(particle_nr),         'Value',  GUI.Internal_Generator_choice(particle_nr));
       set(GUI.handles_Lagrangian_Overrule(particle_nr),        'Value',  GUI.Lagrangian_Coupling_Overrule(particle_nr)); 
       set(GUI.handles_Generator_Minus(particle_nr),            'Value',  GUI.Generator_minus(particle_nr)); 
       set(GUI.handles_Lagrangian_Slider(particle_nr),          'Value',  GUI.Lagrangian_Coupling_Scale(particle_nr)); 
       set(GUI.handles_SumGenerators(3*(particle_nr-1)+1),      'Value',  GUI.Sum_Generators(3*(particle_nr-1)+1)); 
       set(GUI.handles_SumGenerators(3*(particle_nr-1)+2),      'Value',  GUI.Sum_Generators(3*(particle_nr-1)+2)); 
       set(GUI.handles_SumGenerators(3*(particle_nr-1)+3),      'Value',  GUI.Sum_Generators(3*(particle_nr-1)+3)); 
       set(GUI.handles_Fermion_Ninv(particle_nr),     'BackgroundColor',  GUI.color(2+particle_nr,1:3)); 
       set(GUI.handles_Fermion_Cinv(particle_nr),     'BackgroundColor',  GUI.color(2+particle_nr,1:3));   
       set(GUI.handles_Fermion_Pinv(particle_nr),     'BackgroundColor',  GUI.color(2+particle_nr,1:3)); 
       set(GUI.handles_Fermion_Tinv(particle_nr),     'BackgroundColor',  GUI.color(2+particle_nr,1:3));  
       set(GUI.handles_Fermion_Pseu(particle_nr),     'BackgroundColor',  GUI.color(2+particle_nr,1:3));    
       set(GUI.handles_Fermion_Mass(particle_nr),     'BackgroundColor',  GUI.color(2+particle_nr,1:3));    
       set(GUI.handles_edit_Lepton_Mass(3*(particle_nr-1)+1),   'String', num2str(GUI.Lepton_Mass(1))); 
       set(GUI.handles_edit_Lepton_Mass(3*(particle_nr-1)+2),   'String', num2str(GUI.Lepton_Mass(2)));
       set(GUI.handles_edit_Lepton_Mass(3*(particle_nr-1)+3),   'String', num2str(GUI.Lepton_Mass(3)));
       set(GUI.handles_Show_No_Spinors(particle_nr),            'Value',  GUI.Show_No_Spinors(particle_nr));

    end

    set(GUI.handles.checkbox_Use_generators_for_all_particles,  'Value',  GUI.Use_generators_for_all_particles);                                
    set(GUI.handles.checkbox_Enable_Bilinear_choice,            'Value',  GUI.Enable_Bilinear_Field_choice);
    set(GUI.handles.popupmenu_Bilinear_Construction,            'Value',  GUI.Bilinear_Construction_Choice(1));
    set(GUI.handles.checkbox_Show_Vector_Trajectories,          'Value',  GUI.Show_Vector_Trajectories);
    set(GUI.handles.checkbox_Enable_Accumulation,               'Value',  GUI.Enable_Accumulation);
    set(GUI.handles.checkbox_Fermion_Generation_0,              'Value',  GUI.Fermion_Gen_Select(1));
    set(GUI.handles.checkbox_Fermion_Generation_1,              'Value',  GUI.Fermion_Gen_Select(2));
    set(GUI.handles.checkbox_Fermion_Generation_2,              'Value',  GUI.Fermion_Gen_Select(3));
    set(GUI.handles.checkbox_Fermion_Generation_3,              'Value',  GUI.Fermion_Gen_Select(4));
    set(GUI.handles.slider_Visualization_Angle,                 'Value',  30.0);
    set(GUI.handles.slider_Visualization_Scale,                 'Value',  1.5 );
    set(GUI.handles.slider_Visualization_Angle2,                'Value',  30.0);
    set(GUI.handles.slider_Visualization_Scale2,                'Value',  1.75);
    set(GUI.handles.checkbox_Show_Spinor_Current,               'Value',  GUI.Show_Spinor_Current(1));
    set(GUI.handles.checkbox_Show_Spinor_Meshes,                'Value',  GUI.Show_Spinor_Meshes(1));
    set(GUI.handles.popupmenu_Visualize,                        'Value',  GUI.Visualization_choice);
    set(GUI.handles.slider_Time,                                'Value',  1);
    set(GUI.handles.pushbutton_PLAY_PAUSE,                      'String', 'PLAY'); 
    set(GUI.handles.uipanel_Cursor_Line,                        'Position',GUI.Timeline_Cursor_Position );
    set(GUI.handles.text_Selected_Cell_Data,                    'String', '');
    set(GUI.handles.edit_VideoFileName,                         'String',  GUI.VideoFileName ); 

    
    for i = 1:4
        for j = 1:4
          set(GUI.handles_Boson_Vectors(4*(i-1)+j),             'Value',  GUI.Boson_Vector_Select(i,j) );
        end       
    end
end



end

