function matrixBilinearField = UnifiedField_FUN_Calc16x16_BilinearField(fieldLeft,fieldRight,symmetric,GEN)
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% UnifiedField_GUI_Calc16x16_BilinearField()
%
% Calculate the 16x16 Bilinear field matrix
% 
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


matrixLeft         = GEN.I0o * fieldLeft( 1)  ...
                   + GEN.I0x * fieldLeft( 2)  ...  
                   + GEN.I0y * fieldLeft( 3)  ...  
                   + GEN.I0z * fieldLeft( 4)  ...  
                   + GEN.I1o * fieldLeft( 5)  ...
                   + GEN.I1x * fieldLeft( 6)  ...  
                   + GEN.I1y * fieldLeft( 7)  ...  
                   + GEN.I1z * fieldLeft( 8)  ...
                   + GEN.I2o * fieldLeft( 9)  ...
                   + GEN.I2x * fieldLeft(10)  ...  
                   + GEN.I2y * fieldLeft(11)  ...  
                   + GEN.I2z * fieldLeft(12)  ...
                   + GEN.I3o * fieldLeft(13)  ...
                   + GEN.I3x * fieldLeft(14)  ...  
                   + GEN.I3y * fieldLeft(15)  ...  
                   + GEN.I3z * fieldLeft(16);

               
               
matrixRight        = GEN.J0o * fieldRight( 1)  ...
                   + GEN.J0x * fieldRight( 2)  ...  
                   + GEN.J0y * fieldRight( 3)  ...  
                   + GEN.J0z * fieldRight( 4)  ...  
                   + GEN.J1o * fieldRight( 5)  ...
                   + GEN.J1x * fieldRight( 6)  ...  
                   + GEN.J1y * fieldRight( 7)  ...  
                   + GEN.J1z * fieldRight( 8)  ...
                   + GEN.J2o * fieldRight( 9)  ...
                   + GEN.J2x * fieldRight(10)  ...  
                   + GEN.J2y * fieldRight(11)  ...  
                   + GEN.J2z * fieldRight(12)  ...
                   + GEN.J3o * fieldRight(13)  ...
                   + GEN.J3x * fieldRight(14)  ...  
                   + GEN.J3y * fieldRight(15)  ...  
                   + GEN.J3z * fieldRight(16);  
               
matrixBilinearField = matrixLeft/2 * matrixRight/2;  

if symmetric == true
     matrixBilinearField = matrixBilinearField*(-GEN.I3o);
end


end

