function matrixBilinearSpinor = UnifiedField_FUN_Calc_4x4_BilinearSpinor(field,GEN)
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% UnifiedField_GUI_Calc_4x4_BilinearSpinor()
%
% Calculate all the 4x4 Bilinear spinor matrices
% 
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

matrixBilinearSpinor = zeros(4,4,4);



matrixLeft(1,1:4,1:4)  = GEN.io * field( 1)  ...
                       + GEN.ix * field( 2)  ...  
                       + GEN.iy * field( 3)  ...  
                       + GEN.iz * field( 4); 
matrixLeft(2,1:4,1:4)  = GEN.io * field( 5)  ...
                       + GEN.ix * field( 6)  ...  
                       + GEN.iy * field( 7)  ...  
                       + GEN.iz * field( 8);
matrixLeft(3,1:4,1:4)  = GEN.io * field( 9)  ...
                       + GEN.ix * field(10)  ...  
                       + GEN.iy * field(11)  ...  
                       + GEN.iz * field(12);
matrixLeft(4,1:4,1:4)  = GEN.io * field(13)  ...
                       + GEN.ix * field(14)  ...  
                       + GEN.iy * field(15)  ...  
                       + GEN.iz * field(16);

matrixRight(1,1:4,1:4) = GEN.jo * field( 1)  ...
                       + GEN.jx * field( 2)  ...  
                       + GEN.jy * field( 3)  ...  
                       + GEN.jz * field( 4); 
matrixRight(2,1:4,1:4) = GEN.jo * field( 5)  ...
                       + GEN.jx * field( 6)  ...  
                       + GEN.jy * field( 7)  ...  
                       + GEN.jz * field( 8);
matrixRight(3,1:4,1:4) = GEN.jo * field( 9)  ...
                       + GEN.jx * field(10)  ...  
                       + GEN.jy * field(11)  ...  
                       + GEN.jz * field(12);
matrixRight(4,1:4,1:4) = GEN.jo * field(13)  ...
                       + GEN.jx * field(14)  ...  
                       + GEN.jy * field(15)  ...  
                       + GEN.jz * field(16);
               
matrixBilinearSpinor(1,:,:) = squeeze(matrixLeft(1,1:4,1:4)) * squeeze(matrixRight(1,1:4,1:4));               
matrixBilinearSpinor(2,:,:) = squeeze(matrixLeft(2,1:4,1:4)) * squeeze(matrixRight(2,1:4,1:4));               
matrixBilinearSpinor(3,:,:) = squeeze(matrixLeft(3,1:4,1:4)) * squeeze(matrixRight(3,1:4,1:4));               
matrixBilinearSpinor(4,:,:) = squeeze(matrixLeft(4,1:4,1:4)) * squeeze(matrixRight(4,1:4,1:4));                         


end

